// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message       string `json:"message"`
	AccessToken   string `json:"accessToken"`
	AccessExpire  int    `json:"accessExpire"`
	RefreshAfter  int    `json:"refreshAfter"`
	RefreshToken  string `json:"refreshToken,omitempty"`  // 新增
	RefreshExpire int    `json:"refreshExpire,omitempty"` // 新增
}

type RefreshRequest struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RefreshResponse struct {
	AccessToken   string `json:"accessToken"`
	AccessExpire  int    `json:"accessExpire"`
	RefreshToken  string `json:"refreshToken"`
	RefreshExpire int    `json:"refreshExpire"`
}

type ShowRequest struct {
	ShortUrl string `path:"shortUrl" validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}

type SignupRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	RePassword string `json:"re_password"`
	Gender     int    `json:"gender,options=0|1|2,default=0"`
}

type SignupResponse struct {
	Message string `json:"message"`
}
