server:
  http:
    addr: 0.0.0.0:8482
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9492
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:1234@tcp(172.17.0.1:3306)/review?parseTime=True&loc=Local
  redis:
    addr: 172.17.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2025-09-07"
  machine_id: 1
elasticsearch:
  addresses:
    - "http://172.17.0.1:9200"
  index: "review"