app:
  name: "bluebell"
  mod: "dev"
  port: 9090
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "117.72.167.29"
  port: 3306
  user: "yugin"
  password: "Xyj200208#"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
snowflake:
  startTime: "2025-08-05"
  machineID: 1
  